### ISSUE TITLE
Enable variables support in oauth2.0

### ISSUE THREAD

**Issue by YoranSys** [warmuuh/milkman#104]
Hi,

When we try to use variable in oauth form it's seem to not be relative to current environment variable.

**Comment by warmuuh** [comment]
yes, this is currently not supported but surely can be added

**Comment by warmuuh** [comment]
actually, are you sure that this makes sense? whats the actual usecase?
when you fetch a token, it will always be environment-specific, as it wont be "FETCHED" automatically, just refreshed. so you might not want to switch environments for a token.

this assumes that you use environments such as qa/production or such. maybe u use environments totally different.

i actually use it the other way around: have setup multiple keys and reference them in env-variables so that different keys will be used with the same env-var name.

**Comment by YoranSys** [comment]
Thank you,  I will try that way ;)
