### ISSUE TITLE
Sync With Local Directory

### ISSUE THREAD

**Issue by generatives** [warmuuh/milkman#117]
Would it be possible to enable syncing a whole workspace with a local directory? I want to use git to share my workspace with my team members but I want to manage the git repository myself, rather than having the tool checkout and commit for me. If there isn't a function like this already would it be difficult for a newbie to make?

**Comment by warmuuh** [comment]
it actually is kinda supported already:
init some repo and do a commit on your local drive, e.g. 
```bash
git init
touch readme.md && git commit -m "initial commit" && git push
```
then use that directory as url in the git sync setting e.g. `\Users\...\gitrepo` (just add random data to user/password)
after sync, you can do `git restore .` in your repo and you should see the files :)

obviously this is not really an intentional usecase, so this can be streamlined, i guess... 
is this intended to be used like a sync? or like an workspace exporter (i guess, you know that you can export a workspace, but this is not a "sync" feature)?

in general, creating either ([exporters](https://github.com/warmuuh/milkman/blob/master/milkman/src/main/java/milkman/ui/plugin/WorkspaceExporterPlugin.java or [syncs](https://github.com/warmuuh/milkman/blob/master/milkman/src/main/java/milkman/ui/plugin/WorkspaceSynchronizer.java)) just involves implementing one of the linked interfaces and make it known to milkman via SPI, so you can also customize it as you want.

**Comment by warmuuh** [comment]
closed as no response
