### ISSUE TITLE
How do I manage collection variables?

### ISSUE THREAD

**Issue by alexandrehtrb** [warmuuh/milkman#135]
Hello,

How do I manage collection variables, like in Postman? When I import a Postman collection in Milkman, does it import the collection variables along?

**Comment by warmuuh** [comment]
similar to postman, you can have environments which you can modify/edit in the toolbar:
![image](https://user-images.githubusercontent.com/1331628/137262414-f6f5148b-bc87-49b3-a57d-8df82c7ddcdb.png)
you can quickly edit the current environment with `ctrl-e` and also use [quick-edit for variables](https://github.com/warmuuh/milkman/blob/master/docs/features.md#quick-edit-for-variables)

the postman importer supports importing environments but only, if you import a [data-dump](https://learning.getpostman.com/docs/postman/collections/data_formats/#data-dumps)

**Comment by warmuuh** [comment]
ah, sorry, i didnt know this feature. 
no, this is currently not supported nor imported. i currently cant think of a convincing reason to add this, what would this provide over environment-variables / global variables (which are both supported), except maybe keeping the environemnts a bit more clean.

**Comment by warmuuh** [comment]
i would love if you participate. after thinking about this, i am still hesitant to add native support for collection-variables mainly because i want to keep milkman "slick" in the sense that there should be only one way to do things and it shouldnt be overloaded (as i feel that postman suffers feature-creep).

but i do feel that it makes sense to support some kind of import for collection-variables, maybe into a global environment (being always active next to the currently chosen one). I feel this is also something that is easily add-able in the course of hacktoberfest, wdyt? 

if you still feel, that native collection variable support would be beneficial, i am all open for PRs and will provide some pointers for you to get started / how to best tackle that problem

**Comment by warmuuh** [comment]
closing due to missing activity
