### ISSUE TITLE
support environment variables in milkman-auth plugin

### ISSUE THREAD

**Issue by spex66** [warmuuh/milkman#167]
I'm brand new to Milkman, so pls bare with my ignorance.
Trying to figure out what is supported for migrating from Postman, with a focus on OAuth2 flows.

I was able to add the `milkman-auth.jar` to my win64 installation, as `Choco install milkman-plugins` missed it (doesn't contain all as promised :)).

My issue atm:
- Environment-variables (as used to in Postman) seem not to work in auth-plugin, like setting the OAuth2 scope `{{baseUrl}}/.default` and especially for secrets.
- Is this not supported? If yes, is it tricky to add?
![image](https://user-images.githubusercontent.com/1098323/225021222-c103e945-804b-4474-a53d-21e703956bfb.png)

**Comment by warmuuh** [comment]
it is not supported because keys and environments have a different lifecycle, so to say. keys are cached so they are not re-fetched on every request. that means, if you change the environment during two request, the key stays the same.
for what you are trying to achive, i do it like that:
* have a key per environment
* have an environment-variable which points to the right key (env variables can be recursive).
example:
key1: "oauth-svc-prod", key2: "oauth-svc-qa"

and then, you can have a env-variable "oauth-svc" which points to either {{key:oauth-svc-prod}} or {{key:oauth-svc-qa}}
