### ISSUE TITLE
Issue opening Milkman on Windows

### ISSUE THREAD

**Issue by IsiR19** [warmuuh/milkman#78]
![Annotation 2020-12-01 160556](https://user-images.githubusercontent.com/23460216/100751247-bf9efc80-33ef-11eb-8403-4bf9f7b9244e.png)

**Comment by warmuuh** [comment]
is this a fresh install? or upgrading an existing app?

**Comment by IsiR19** [comment]
Hi, the application was running yesterday, closed it and re-opened it about an hour ago and have been getting this error.

**Comment by IsiR19** [comment]
I did run a sync with my bit bucket repo before I closed it

**Comment by warmuuh** [comment]
hm, there might be some issue in the sync then although i cannot reproduce it, whatever i try.

to recover, you can at least manually revert unwanted changes in the git-repo.
to fix your local data, you might wanna try the nightly version i just pushed, this might make your application start again.
Alternatively remove & reimport the persistence in milkman (delete database.db in the milkman-directory, but this will remove every workspace you had).

some more details:
apparently, a collection got loaded with "null" instead of empty list of requests. might be interesting if the git repo has any null (or nonexistant) "requests" entries in the collections.json file. i added a minor fix to initialize the requests with empty list which should cover some cases, but as i cannot reproduce it, it is hard to say if this fixes it

**Comment by IsiR19** [comment]
Thank you deleting the database file seems to have resolved the issue.

Thank you for the assistance
